services:
  - type: web
    name: ethio-digital-trading
    env: docker
    plan: free
    dockerfilePath: aa.Dockerfile
    buildFilter:
      paths:
        - Dockerfile
        - render.yaml
        - .env
        - composer.json
    envVars:
      - key: APP_NAME
        value: "Ethio Digital Trading"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://ethio-digital-trading.onrender.com

      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug

      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-production-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-db-name
      - key: DB_USERNAME
        value: your-db-username
      - key: DB_PASSWORD
        value: your-db-password

      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120

      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local

      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailpit
      - key: MAIL_PORT
        value: 1025
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: "Ethio Digital Trading"

      - key: GOOGLE_TRANSLATE_API_KEY
        value: api-key-abc123XYZ789
