services:
  - type: web
    name: ethio-digital-trading
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://ethio-digital-trading.onrender.com

      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug

      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: dpg-d0kfqiruibrs739gpvsg-a
      - key: DB_PORT
        value: 3306 # Check if this should be 3306 for MySQL
      - key: DB_DATABASE
        value: laravel10role
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: oOzLnrmGnvFlSvqUrQZIcywOZrsOhK8Z

      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120

      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local

      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailpit
      - key: MAIL_PORT
        value: 1025
      - key: MAIL_FROM_ADDRESS
        value: aminsaidaliyi55@gmail.com
      - key: MAIL_FROM_NAME
        value: "Ethio Digital Trading"

      - key: GOOGLE_TRANSLATE_API_KEY
        value: api-key-abc123XYZ789
    ports:
      - port: 10000
